const dataOdierna= new Date();
const dataOdiernaMs=dataOdierna.getTime();
const dataDomani= new Date("August 24,2023 9:30");
const dataDomaniMs=dataDomani.getTime();
let tempoRimanente=dataDomaniMs-dataOdiernaMs;
let day= document.getElementById('days');
let minute= document.getElementById('minutes');
let second= document.getElementById('seconds');
let countDown= setInterval(function(){
    let secondiTot= tempoRimanente/1000;
    let cMinute= secondiTot / 60;
    cOre= parseInt((secondiTot/60)/60);
    cMinute=cMinute-(cOre*60);
    let cSecond= parseInt((cMinute-parseInt(cMinute))*60);
    cMinute=parseInt(cMinute);
    console.log('ORE:'+cOre);
    console.log('MINUTI:'+cMinute);
    console.log('SECONDI:'+cSecond);
    secondiTot=secondiTot-10;
},10);
